### ISSUE TITLE
请问后期后有小程序的版本吗

### ISSUE THREAD

**Issue by pcwuyu** [Wsine/seekpassword#3]
看了您在少数派的文章，发现现在只有网页版。
如果有小程序的版本就好了，这样就可以实现所有客户端都方便使用了。

**Comment by Wsine** [comment]
我不太理解。有什么客户端是不能使用网页版而能使用小程序？

**Comment by pcwuyu** [comment]
😃用习惯了还是小程序更加方便啊

Zhengyuan Wei <notifications@github.com> 于2019年7月7日周日 下午9:29写道：
